### ISSUE TITLE
panic: runtime error: slice bounds out of range [1:0]

### ISSUE THREAD

**Issue by jsamson87** [NeaGogu/Kaspersky-to-csv#1]
I get this error.

panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
main.readWebsites(0xc000123e50)
        /home/gogu/Projects/Golang/Kaspersky-to-csv/website.go:41 +0x535
main.main()
        /home/gogu/Projects/Golang/Kaspersky-to-csv/main.go:40 +0x1fc

I already have removed all notes entries from txt file.

Found the issue. It cannot handle some very long urls for example:
https://customer.bmwgroup.com/one/signin.html?client_id=dbf0a542-ebd1-4ff0-a9a7-55172fbfce35&redirect_uri=https:%2F%2Fwww.bmw-connecteddrive.com%2Fapp%2Fstatic%2Fexternal-dispatch.html&response_type=token&scope=authenticate_user%20fupo&state=eyJtYXJrZXQiOiJkZSIsImxhbmd1YWdlIjoiZGUiLCJkZXN0aW5hdGlvbiI6InVzZXJEYXNoYm9hcmRQYWdlIiwicGFyYW1ldGVycyI6Int9In0&locale=DE-de

Would be great if you can fix it, cause I'm don't konw how. My coding skills are very limited ;-)

**Comment by NeaGogu** [comment]
Hi

Unfortunately, I cannot recreate the same error with the URL you have provided. Maybe you can help me with more info

1. What OS are u running? Check if you used the wrong executable though I doubt that is the issue

2. Have you tried to change the delimiter to something else (by default it is ","). Try changing it with  `-delimiter "<your delimiter>"`

3. Also, can you check if the structure of the password file is the following?

```
Websites

Website name: github
Website URL: https://github.com/NeaGogu/Kaspersky-to-csv
Login name: aNiceName
Login: aNiceUsername
Password: aNicePassword
Comment:

---

Website name: github
Website URL: https://github.com/NeaGogu/Kaspersky-to-csv
Login name: aNiceName
Login: aNiceUsername
Password: aNicePassword
Comment:

---
```

**Comment by ghost** [comment]
Same issue here today:

![image](https://user-images.githubusercontent.com/60049112/158680240-26d7cea0-254e-4c6d-8a1e-b12baef0e82b.png)

Im on Windows 10 Pro 64Bits.


here is a example of mi password.txt
![2022_03_16_13_06_18](https://user-images.githubusercontent.com/60049112/158681114-2e55522d-7209-4b6f-9679-44ebe77a2b56.png)

I remove all the notes, Applications, etc and only keep "Website name"

**Comment by NeaGogu** [comment]
I have pushed a new version that might fix this issue. Please tell me if it worked. 

> Also double-check to have "Websites"  written exactly like that at the beginning of the file and do not change the original structure of the file (you may leave the Notes and Applications in there)

**Comment by jsamson87** [comment]
> Hi
> 
> Unfortunately, I cannot recreate the same error with the URL you have provided. Maybe you can help me with more info
> 
> 1. What OS are u running? Check if you used the wrong executable though I doubt that is the issue
> 2. Have you tried to change the delimiter to something else (by default it is ","). Try changing it with  `-delimiter "<your delimiter>"`
> 3. Also, can you check if the structure of the password file is the following?
> 
> ```
> Websites
> 
> Website name: github
> Website URL: https://github.com/NeaGogu/Kaspersky-to-csv
> Login name: aNiceName
> Login: aNiceUsername
> Password: aNicePassword
> Comment:
> 
> ---
> 
> Website name: github
> Website URL: https://github.com/NeaGogu/Kaspersky-to-csv
> Login name: aNiceName
> Login: aNiceUsername
> Password: aNicePassword
> Comment:
> 
> ---
> ```

- I'm using Win 11
- delimiter is not the problem. I already checked that
- I will check, if there is any special character within the password
- I will also try new version this evening

Many thx!
